events {}

http {
    server {
        listen 80;
        server_name bfujournal.ru www.bfujournal.ru;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name bfujournal.ru www.bfujournal.ru;

        ssl_certificate /etc/letsencrypt/live/bfujournal.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/bfujournal.ru/privkey.pem;

        location / {
            proxy_pass http://frontend:80/;
            proxy_set_header Host $host;
        }

        location /api/ {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://backend:8000;
            proxy_set_header Host $host;
        }
    }
}
